### ISSUE TITLE
Not possible to normalize jsonld

### ISSUE THREAD

**Issue by ppwfx** [gobengo/activitystreams2-spec-scraped#12]
Hey gobengo, 

sry for being that annoying, but I still got some complaints ofc :D 

I found some time to proceed with generating golang structs from jsonld. 
My approach is to normalize it to triples. Unfortunately it's not possible to do that with the jsonld you generated.

Please have a look here:

https://json-ld.org/playground/
https://search.google.com/structured-data/testing-tool

Using this url
https://github.com/gobengo/activitystreams2-spec-scraped/blob/master/data/activitystreams-vocabulary/1528589057-compacted.json

**Comment by gobengo** [comment]
@21stio Will you elaborate more? I am able to normalize it using the playground: [here is a permalink](https://json-ld.org/playground/#startTab=tab-normalized&json-ld=https%3A%2F%2Fraw.githubusercontent.com%2Fgobengo%2Factivitystreams2-spec-scraped%2Fmaster%2Fdata%2Factivitystreams-vocabulary%2F1528589057-compacted.json)

some relevant triples:
```
<https://www.w3.org/TR/activitystreams-vocabulary/> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Ontology> .
<https://www.w3.org/TR/activitystreams-vocabulary/> <http://www.w3.org/2002/07/owl#imports> _:c14n21 .
<https://www.w3.org/TR/activitystreams-vocabulary/> <http://www.w3.org/2002/07/owl#imports> _:c14n24 .
<https://www.w3.org/TR/activitystreams-vocabulary/> <http://www.w3.org/2002/07/owl#imports> _:c14n288 .
<https://www.w3.org/TR/activitystreams-vocabulary/> <http://www.w3.org/2002/07/owl#imports> _:c14n334 .
<https://www.w3.org/TR/activitystreams-vocabulary/> <http://www.w3.org/2002/07/owl#imports> _:c14n387 .
```

"The AS2 vocabulary is an Ontology. The AS2 vocabulary imports these other Ontologies."

which imports the Actor Types Ontology/section

```
_:c14n288 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Ontology> .
_:c14n288 <http://www.w3.org/2002/07/owl#members> <https://www.w3.org/ns/activitystreams#Application> .
_:c14n288 <http://www.w3.org/2002/07/owl#members> <https://www.w3.org/ns/activitystreams#Group> .
_:c14n288 <http://www.w3.org/2002/07/owl#members> <https://www.w3.org/ns/activitystreams#Organization> .
_:c14n288 <http://www.w3.org/2002/07/owl#members> <https://www.w3.org/ns/activitystreams#Person> .
_:c14n288 <http://www.w3.org/2002/07/owl#members> <https://www.w3.org/ns/activitystreams#Service> .
```

which has the member as:Person

```
<https://www.w3.org/ns/activitystreams#Person> <http://schema.org/workExample> <https://www.w3.org/TR/activitystreams-vocabulary/#ex39-jsonld> .
<https://www.w3.org/ns/activitystreams#Person> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Class> .
<https://www.w3.org/ns/activitystreams#Person> <http://www.w3.org/2000/01/rdf-schema#comment> "Represents an individual person." .
<https://www.w3.org/ns/activitystreams#Person> <http://www.w3.org/2000/01/rdf-schema#subClassOf> _:c14n338 .
<https://www.w3.org/ns/activitystreams#Person> <https://www.w3.org/ns/activitystreams#name> "Person" .
<https://www.w3.org/ns/activitystreams#Person> <https://www.w3.org/ns/activitystreams#url> <https://www.w3.org/TR/activitystreams-vocabulary/#dfn-person> .
```

**Comment by ppwfx** [comment]
ah okay, Im sorry. I meant normalize in a way that gets rid of nesting.  Like e.g. https://schema.org/Person.jsonld. 

Receiving it that way makes it just way easier to generate types from it.

**Comment by gobengo** [comment]
Maybe you want it flattened? https://github.com/gobengo/activitystreams2-spec-scraped/pull/13/commits/37a237d590858e44a3009e3229b40365308753ff#diff-26d2f282a970bfcf88343202f8f6f08d

https://github.com/gobengo/activitystreams2-spec-scraped/pull/13/commits/37a237d590858e44a3009e3229b40365308753ff#diff-0c5d2e613181c3ff63a4cbbbff9da8d1
