### ISSUE TITLE
Map 'example' to useful linked data URI

### ISSUE THREAD

**Issue by gobengo** [gobengo/activitystreams2-spec-scraped#5]
The only term I have unmapped to an existing vocab in my output is 'example', which I use to point to examples from the AS2 spec for each Activity Type or Property.

https://github.com/gobengo/activitystreams2-spec-scraped/blob/f211741c19e17c39dbcf9108f58fa5fe2de17faa/data/activitystreams-vocabulary/1528589057.json#L87

I looked around, and can't easily find a vocabulary that defines a property whose semantics are something like:
* domain: `rdf:Property`
* description: "The object is an example of the subject, documenting a realistic Resource that makes use of the property"
* range: Literal would be ok, but rdfs:Resource would be better for what I've got

Any ideas @csarven ?

**Comment by gobengo** [comment]
Many of these will work. http://lov.okfn.org/dataset/lov/terms?q=example

**Comment by gobengo** [comment]
http://schema.org/workExample

**Comment by csarven** [comment]
workExample is probably just fine. FYI, I used `http://schema.org/hasPart` to connect with `http://purl.org/spar/fabio/Script` in https://www.w3.org/TR/ldn/ - could be interpreted as an implied "example".

**Comment by gobengo** [comment]
@csarven Thanks for your advice!
